module.exports = {
	printWidth: 100,
	tabWidth: 2,
	useTabs: true,
	semi: false,
	vueIndentScriptAndStyle: false,
	singleQuote: true,
	quoteProps: 'as-needed',
	trailingComma: 'none',
	bracketSpacing: true,
	bracketSameLine: false,
	jsxBracketSameLine: false,
	jsxSingleQuote: false,
	arrowParens: 'always',
	insertPragma: false,
	requirePragma: false,
	proseWrap: 'never',
	htmlWhitespaceSensitivity: 'strict',
	endOfLine: 'lf'
}
